name: CI/CD Demo

on:
  push:          # la accion que gatillara este pipeline
    branches:    # se gatillara a esta rama
      - main
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest  # es runner  en gitlab -> en jenkins parace que es en el mismo server donde se ejecuta
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # que actions vas a usar, con esto your workflow can access al repo (clona) y luego push (definido arriba en on) https://github.com/actions/checkout
      
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: run tests   # antes de construir el codigo realizas test
        run: |
          pytest test/test.py
      
      - name: build docker image
        run: |  # github.sha es el hash del commit (al hacer git log) colocamos para etiquetarlo
          docker build -t ${{secrets.DOCKER_USERNAME}}/appdemocopy:${{ github.sha }} .  
      
      - name: docker login  
        uses: docker/login-action@v2  # para loguerate al registri de docker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push docker image
        run: |  # Recordar DOCKER_USERNAME=edw1
          docker push ${{ secrets.DOCKER_USERNAME }}/appdemocopy:${{ github.sha }}  

  #   outputs:
  #     image: edw1/appdemocopy:${{ github.sha }}
  
  cd:
    needs: ci  # para que se ejecute luego de ci y no en parallelo
    runs-on: ubuntu-latest  

    steps:
      - name: coneccion a los servers
        uses: appleboy/ssh-action@v1
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/appdemocopy:${{ github.sha }} 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOCKER_IMAGE # usamos la env definida antes
          script: |  # permite ejecutar comandos ssh linux y no podra entender variables de githubactions por lo que creamos env
            echo "descargando la nueva version"
            docker pull $DOCKER_IMAGE
            echo "stop current version"
            sleep 1
            API=$(docker ps -q -f name=api)
            if [ ! -z $API ] then 
             docker stop $API
             docker rm $API
            fi 
            docker run -d --name newapp -p 80:8080 $DOCKER_IMAGE
                
      - name: check service ok
        env:
          ENPOINT: ${{ secrets.ENPOINT }}
        run: |
          RESPONSE=$(curl -IXGET -s http://${{ secrets.ENPOINT }}:80/status | head -n 1)
          if [ $RESPONSE -ne "200" ] then
            echo "service no ok"
          fi
          echo "servicio ok normalemnte se envia por correo" 
  # cd:
  #   needs: ci
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: AWS authentication
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
  #         role-duration-seconds: 1200
  #         role-session-name: ${{ github.sha }}
  #         aws-region: us-east-1
      
  #     - name: update deployment
  #       run: |
  #         aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1
  #         kubectl set image deployment/python-fastapi-deployment api=edw1/faapi:${{ needs.ci.outputs.image }} -n app
        
  
